name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        bash ${GITHUB_WORKSPACE}/scripts/build.sh ${GITHUB_WORKSPACE}
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: |
          build
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: build
